lesson-5
savchenkoanna/test-savchenko pull request #2
Opened 2018-06-21 15:21 UTC by savchenkoanna

2018-06-22 15:18 UTC, Afelua requested changes

2018-06-22 15:18 UTC, Afelua commented on styles.css
> + .menu {
Чтобы убрать точки, нужно для элемента ul добавить `list-style: none;`

2018-06-22 15:18 UTC, Afelua commented on index.html
> +		<img src="./images/logo.png">
Нужно задать отступы для логотипа

2018-06-22 15:18 UTC, Afelua commented on index.html
> +			<ul class="icons">
Делается так:

ul - один на все элементы, а каждый в отдельности пишется в li. т.е. такая должна быть структура:

`<ul>
	<li>Item 1</li>
	<li>Item 2</li>
	<li>Item 3</li>
</ul>`


и т.д.

2018-06-22 15:18 UTC, Afelua commented on styles.css
> +	background: : #ffffff;
Такой код не сработает. Должно быть `background: #ffffff;` с 1 символом двоеточия.

2018-06-22 15:18 UTC, Afelua commented on styles.css
> +.white_block {
Этот селектор .white_block получается вложенным в .big_title. Такого не должно быть. Сначала пишем для .big_title {}, затем .white_block{} . Сейчас по данной причине стили для .white_block не подхватываются.

2018-06-22 15:18 UTC, Afelua commented on styles.css
> +	font-size: 14 px;
Нужно писать слитно: `font-size: 14px;`. Проверить везде.

2018-06-22 15:18 UTC, Afelua commented on index.html
>  		<section>
Нужно поместить картинку с белым блоком в 1 ряд. Сделать это можно через display: flex; Также стоит задать их ширину и позиционировать по центру:
width: 880px; (подбираете нужное)
margin: 0 auto;

2018-06-22 15:18 UTC, Afelua commented on styles.css
> +.readmore_in_section {
Проблема с цветом ссылок связана с незакрытыми } у класса .big_title (см. выше)

2018-06-23 14:29 UTC, savchenkoanna commented on styles.css
> + .menu {
done

2018-06-23 14:31 UTC, savchenkoanna commented on styles.css
> +	background: : #ffffff;
done

2018-06-23 14:33 UTC, savchenkoanna commented on styles.css
> +	font-size: 14 px;
done

2018-06-23 14:34 UTC, savchenkoanna commented on styles.css
> +.readmore_in_section {
done

2018-06-23 14:49 UTC, savchenkoanna commented on index.html
> +		<img src="./images/logo.png">
done

2018-06-23 15:35 UTC, savchenkoanna commented on index.html
>  		<section>
я выравняла)

2018-06-23 15:36 UTC, savchenkoanna commented on styles.css
> +.white_block {
вроде получилось)

2018-06-23 15:36 UTC, savchenkoanna commented on index.html
> +			<ul class="icons">
только я не поняла. что здесь не так)

2018-06-24 20:06 UTC, Afelua commented on index.html
> +			<ul class="icons">
Это - сам подход к написанию списков:

  <ul>
    <li>Чебурашка</li>
    <li>Крокодил Гена</li>
    <li>Шапокляк</li>
  </ul>

Всегда элемент ul один на весь список, а под каждый элемент задается li - http://htmlbook.ru/html/ul

2018-06-24 20:42 UTC, Afelua requested changes

2018-06-24 20:42 UTC, Afelua commented on fonts.css
> +	font-family: AvenirNext;
Всегда при записи шрифта прописывайте запасной вариант, например, sans-serif. Понадобится, если подключение к интернету будет потеряно.

2018-06-24 20:42 UTC, Afelua commented on index.html
> +		<section class="container">
Для всего списка с преимуществами не хватает отступов сверху и снизу. Кстати, элементу можно присваивать несколько классов (`<section class="container container_benefits">`)

2018-06-24 20:42 UTC, Afelua commented on index.html
> +					<p class="icons_text">Text №1</p>
Нужно скопировать актуальный текст с Фотошопа. Проверить везде.

2018-06-24 20:42 UTC, Afelua commented on styles.css
> +  margin-left: 150px;
Лучше сделать выравнивание элемента по центру экрана так:
`    width: 1000px; // подбираете нужно значение
    margin: 0 auto;`.

Тогда элемент всегда будет по центру вне зависимости от размера экрана.

2018-06-24 20:42 UTC, Afelua commented on styles.css
> +  margin-left: 150px;
После этого margin-left: 150px;  и margin-right убираем, они будут лишними.

2018-06-24 20:42 UTC, Afelua commented on styles.css
> +width: 800px;
800 слишком много, по макету он около 400px

2018-06-24 20:42 UTC, Afelua commented on styles.css
> +height: 394px;
Лучше не задавать четкую высоту (блок не сможет подстроиться по вертикали, если мы вдруг добавим новый текст), и добиться отступов сверху и снизу padding.

2018-06-24 20:42 UTC, Afelua commented on styles.css
> +height: 394px;
Чтобы выровнить весь текст внутри него по центру, нужно написать text-align: center;

2018-06-24 20:42 UTC, Afelua commented on index.html
> +				<img src="./images/icon5.svg" width="50">
Думаю, что картинка не 50px, смотрится очень большой:

<img width="202" alt="screen shot 2018-06-24 at 23 22 47" src="https://user-images.githubusercontent.com/8777546/41823245-874a7128-7805-11e8-801c-fa474e1fb777.png">

2018-06-24 20:42 UTC, Afelua commented on index.html
> +		<h1 class="title">FITNESS IN A CAN/</h1>
Весь большой текст мы не пишем в верхнем регистре, а задаем через CSS-свойство: text-transform: uppercase. Проверить везде. в т.ч. для .big_title и small_title

2018-06-24 20:42 UTC, Afelua commented on styles.css
> +font-size: 14px;
Стоит проверить цвет текста в Фотошопе, он не черный.

2018-06-24 20:42 UTC, Afelua commented on styles.css
> +padding-left: : : 120px;
Код с двумя двоеточиями никогда не сработает

2018-06-24 20:42 UTC, Afelua commented on index.html
> +	<footer class="footer">
Структура должна быть следующей - https://plnkr.co/edit/izjkVmKBipGhSOqNQXFB?p=preview

2018-06-24 20:42 UTC, Afelua commented on styles.css
> +width: 201px;
Нужно задать padding и margin, при этом высоту и ширину лучше убрать (будет корректнее работать при масштабировании страницы)

2018-06-24 20:42 UTC, Afelua commented on styles.css
> +.buttom {
Текст на кнопке белый + см. комменты к .input.

2018-06-24 20:42 UTC, Afelua commented on index.html
> +					<img src="./images/fb.svg">
Мы картинку добавляем через псевдоэлемент, т.е. в обычном HTML тег img убираем (пройтись ко всем)

2018-06-24 20:42 UTC, Afelua commented on styles.css
> +.social-icon:before{
У вас у основного элемента класс .social-icon1, а прописываете вы псевдоэлемент к классу .social-icon . Т.е. классы разные, псевдоэлемент никогда не появится. Пройтись по всем.

2018-06-24 20:42 UTC, Afelua commented on index.html
> +			<img class="psevdo" src="./images/img1.jpg">
На изображения нельзя навешивать псевдоэлемент, нам нужно организовать еще один div, в котором будет и картинка, и текст (по аналогии с примером на уроке)

2018-06-25 13:36 UTC, savchenkoanna commented on styles.css
> +  margin-left: 150px;
готово

2018-06-25 13:39 UTC, savchenkoanna commented on styles.css
> +width: 800px;
готово

2018-06-25 13:45 UTC, savchenkoanna commented on styles.css
> +  margin-left: 150px;
готово

2018-06-25 13:45 UTC, savchenkoanna commented on styles.css
> +width: 800px;
готово

2018-06-25 14:07 UTC, savchenkoanna commented on index.html
> +		<section class="container">
готово

2018-06-25 14:10 UTC, savchenkoanna commented on styles.css
> +padding-left: : : 120px;
готово

2018-06-26 13:54 UTC, savchenkoanna commented on fonts.css
> +	font-family: AvenirNext;
готово

2018-06-26 14:00 UTC, savchenkoanna commented on styles.css
> +height: 394px;
отступы сделала

2018-06-26 14:03 UTC, savchenkoanna commented on index.html
> +				<img src="./images/icon5.svg" width="50">
готово

2018-06-26 14:05 UTC, savchenkoanna commented on index.html
> +		<h1 class="title">FITNESS IN A CAN/</h1>
готово

2018-06-26 14:07 UTC, savchenkoanna commented on styles.css
> +font-size: 14px;
готово

2018-06-26 14:12 UTC, savchenkoanna commented on index.html
> +					<p class="icons_text">Text №1</p>
готово

2018-06-26 14:29 UTC, savchenkoanna commented on index.html
> +					<img src="./images/fb.svg">
готово

2018-06-26 14:31 UTC, savchenkoanna commented on styles.css
> +.social-icon:before{
готово

2018-06-26 14:44 UTC, savchenkoanna commented on index.html
> +	<footer class="footer">
сделала

2018-06-26 14:51 UTC, savchenkoanna commented on styles.css
> +width: 201px;
у меня все едет, когда добавляю padding

2018-06-26 14:51 UTC, savchenkoanna commented on index.html
> +			<ul class="icons">
у меня все едет, когда исправляю, а так нормально вроде похоже на макет

2018-06-26 14:52 UTC, savchenkoanna commented on styles.css
> +.buttom {
текст белый сейчас

2018-06-26 15:41 UTC, savchenkoanna commented on index.html
> +			<img class="psevdo" src="./images/img1.jpg">
готово, но немного поехало все

2018-06-26 23:49 UTC, Afelua requested changes

2018-06-26 23:49 UTC, Afelua commented on index.html
> +			<div class="text-hover">
У вас неправильная структура для элемента, текст при наведении должен быть внутри общего контейнера с ним и картинкой:

			<div class="psevdo">
				<div class="text-hover">
					<h2 class="big_title">Fitness first</h2>
					<h3 class="small_title">Its all about</h3>
				</div>
			</div>

2018-06-26 23:49 UTC, Afelua commented on styles.css
> +.text-hover{
Будет полезно выравнить текст по центру: text-align: center;

2018-06-26 23:49 UTC, Afelua commented on styles.css
> +  top: 1100px;
Очень большие показатели, текст уедет за пределы экрана.

2018-06-26 23:49 UTC, Afelua commented on index.html
> +			<ul class="icons">
Неправильная структура и сейчас, должно быть так:

			<ul class="icons">
				<li>
					<img src="./images/icon1.svg">
					<h2 class="icons_title">Resourses</h2>
					<p class="icons_text">Easily manage your inspiration and work-in-progress by dragging images into projects and sharable client groups.</p>
					<a href="#" class="explore_more">Explore more</a>
				</li>
				<li>
					<img src="./images/icon2.svg">
					<h2 class="icons_title">Training & Funding</h2>
					<p class="icons_text">Easily manage your inspiration and work-in-progress by dragging images into projects and sharable client groups. </p>
					<a href="#" class="explore_more">Explore more</a>
				</li>
				<li>
					<img src="./images/icon3.svg">
					<h2 class="icons_title">Connect</h2>
					<p class="icons_text">Easily manage your inspiration and work-in-progress by dragging images into projects and sharable client groups.</p>
					<a href="#" class="explore_more">Explore more</a>
				</li>
				<li>
					<img src="./images/icon4.svg">
					<h2 class="icons_title">Comminucate</h2>
					<p class="icons_text">Easily manage your inspiration and work-in-progress by dragging images into projects and sharable client groups.</p>
					<a href="#" class="explore_more">Explore more</a>
				</li>
			</ul>

2018-06-26 23:49 UTC, Afelua commented on index.html
> +		<ul  class="footer-menu">
Структура списка все равно некорректна, должна быть такой:

		<ul  class="footer-menu">
			<li>
				<a href="#" class="social-icon1"></a>
			</li>

			<li>
				<a href="#" class="social-icon2"></a>
			</li>

			<li>
				<a href="#" class="social-icon3"></a>
			</li>

			<li>
				<a href="#" class="social-icon4"></a>
			</li>
		</ul>

2018-06-26 23:49 UTC, Afelua commented on index.html
> +		 <div class="footer-container">
footer-menu тоже должно быть внутри него.

2018-06-26 23:49 UTC, Afelua commented on styles.css
> +margin: 0 auto;
Стоит также ограничить по ширине. После этого padding-left: 120px; будет лишним

2018-06-26 23:49 UTC, Afelua commented on styles.css
> +  background-image: url('./images/In.svg');
Не отображается иконка соц. сети, не найден файл.

2018-06-27 10:09 UTC, savchenkoanna commented on index.html
> +			<ul class="icons">
готово! наконец-то поняла)

2018-06-27 10:11 UTC, savchenkoanna commented on index.html
> +			<div class="text-hover">
готово, наконец-то поняла!)

2018-06-27 10:12 UTC, savchenkoanna commented on styles.css
> +.text-hover{
готово

2018-06-27 10:15 UTC, savchenkoanna commented on styles.css
> +  top: 1100px;
поняла теперь, в чем проблема была, спасибо!

2018-06-27 10:16 UTC, savchenkoanna commented on styles.css
> +  background-image: url('./images/In.svg');
готово

2018-06-27 10:18 UTC, savchenkoanna commented on index.html
> +		<ul  class="footer-menu">
да. исправила

2018-06-27 11:27 UTC, savchenkoanna commented on styles.css
> +margin: 0 auto;
готово

2018-06-27 14:04 UTC, Afelua approved these changes

2018-06-27 14:48 UTC, merged